### ISSUE TITLE
[ Week 6] 6주차 워크북 미션 

### ISSUE THREAD

**Issue by gyjeong021** [DS-UMC-7th/UMC-7th-Zero#3]
### 🛠 Mission

1. N+1 문제 해결할 수 있는 여러 방법 조사
2. 2주차 미션 때 했던 화면에 대한 쿼리를 QueryDSL로 작성하여 리팩토링

### 📝 To-do

- [x] QueryDSL 기본 설정
- [x] QueryDSL 설정 파일 생성
- [x] QueryDSL 쿼리 작성

### 🔍 접근 방법

-
